/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalkamera;

/**
 *
 * @author USER
 */
import javax.swing.JOptionPane; // membuat pesan dialog
import java.sql.*; // untuk menampilkan data dara perintah query
import java.util.*;
import java.text.SimpleDateFormat;

public class formAnggota extends javax.swing.JFrame {
    

    /**
     * Creates new form formAnggota
     */
    String judulKolom[]={"ID Anggota","nama angggota","tempat lahir","jenis kelamin","status","Alamat","telp"};
    String sqlAnggota="SELECT*FROM anggota";
    int LebarKolom[]={100,300,150,100,150,200,400,100};
    public formAnggota() {
        initComponents();
        this.setLocationRelativeTo(null);
new     ConfigDB().tampilTabel(judulKolom, sqlAnggota, JTableAnggota);
new     ConfigDB().aturLebarKolom(JTableAnggota, LebarKolom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTgl = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtTempat = new javax.swing.JTextField();
        cmbJKL = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableAnggota = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtTgl.setDateFormatString("yyyy-MM-dd");

        jLabel1.setText("ID Anggota");

        jLabel2.setText("Nama Lengkap");

        jLabel3.setText("Tempat Lahir");

        jLabel4.setText("Tanggal Lahir");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Status");

        jLabel7.setText("Alamat");

        jLabel8.setText("Telp");

        txtTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempatActionPerformed(evt);
            }
        });

        cmbJKL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbJKL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJKLActionPerformed(evt);
            }
        });

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        JTableAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableAnggota);

        jButton5.setText("refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtCari.setText("jTextField1");
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNama))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbJKL, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelp)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAlamat)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTempat, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtID)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtCari)
                            .addGap(18, 18, 18)
                            .addComponent(jButton5))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbJKL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(328, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
if (
(txtID.getText().isEmpty()) &&(txtNama.getText().isEmpty()) && (txtTempat.getText().isEmpty())
&& (txtTgl.getDate().equals(null)) && (txtAlamat.getText().isEmpty()) && (txtTelp.getText().isEmpty())
        && (cmbJKL.getSelectedItem()==".: Pilih Data :.") && (cmbStatus.getSelectedItem()==".: Pilih Data :.")
) {
JOptionPane.showMessageDialog(null,"Silahkan pilih data sebelum proses ubah ");
JTableAnggota.requestFocus();
} else{
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
String TGL =sdf.format(txtTgl.getDate());
String SQL="UPDATE anggota SET nama='"+txtNama.getText()+"',tempat_lahir='"+txtTempat.getText()+"',tgl_lahir='"+
TGL+"',jkl='"+String.valueOf(cmbJKL.getSelectedItem()) +"',status='"+String.valueOf(cmbStatus.getSelectedItem())
+"',alamat='"+txtAlamat.getText()+"', telp='"+txtTelp.getText()+"' WHERE IDAnggota='"+txtID.getText()+"'";
new ConfigDB().ubahData(SQL);
new ConfigDB().tampilTabel(judulKolom, sqlAnggota, JTableAnggota);
new ConfigDB().aturLebarKolom(JTableAnggota, LebarKolom);
}
} catch (Exception e)
{
System.out.print(e.toString());
    }//GEN-LAST:event_jButton2ActionPerformed
   }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
if (txtID.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"ID Anggota belum diisi");
txtID.requestFocus();
}else
if(txtNama.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"Nama Anggota belum diisi");
txtNama.requestFocus();
}else
if(txtTempat.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"Tempat Lahir Anggota belum diisi");
txtTempat.requestFocus();
}else
if(cmbJKL.getSelectedItem()==".: Pilih Data :."){
JOptionPane.showMessageDialog(null,"Jenis Kelamin Anggota belum diisi");
cmbJKL.requestFocus();
} else
if(cmbStatus.getSelectedItem()==".: Pilih Data :."){
JOptionPane.showMessageDialog(null,"Status Anggota belum diisi");
cmbStatus.requestFocus();
}else
if(txtAlamat.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"ALamat Anggota belum diisi");
txtAlamat.requestFocus();
}else
if(txtTelp.getText().isEmpty()){
JOptionPane.showMessageDialog(null,"Nomor Telp Anggota belum diisi");
txtTelp.requestFocus();
} else
if (new ConfigDB().duplikasiData("anggota","IDAnggota",txtID.getText())==true){
JOptionPane.showMessageDialog(null,"ID Anggota sudah terdaftar");
Statement st = new ConfigDB().koneksi.createStatement();
ResultSet rs = st.executeQuery("SELECT*FROM anggota WHERE IDAnggota='"+txtID.getText()+"'");
if(rs.next()){
txtNama.setText(rs.getString("nama"));
txtTempat.setText(rs.getString("tempat_lahir"));
SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
txtTgl.setDate(dt.parse(rs.getString("tgl_lahir")));
cmbJKL.setSelectedItem(String.valueOf(rs.getString("jkl")));
cmbStatus.setSelectedItem(String.valueOf(rs.getString("status")));
txtAlamat.setText(rs.getString("alamat"));
txtTelp.setText(rs.getString("telp"));
}
}
else{
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
String TGL =sdf.format(txtTgl.getDate());
String SQL ="INSERT INTO anggota VALUES ('"+txtID.getText()+"','"+txtNama.getText()+"','"+txtTempat.getText()
+"','"+TGL+"','"+String.valueOf(cmbJKL.getSelectedItem()) +"','"+String.valueOf(cmbStatus.getSelectedItem())
+"','"+txtAlamat.getText()+"','"+txtTelp.getText()+"')";
new ConfigDB().simpanData(SQL);
new ConfigDB().tampilTabel(judulKolom, sqlAnggota, JTableAnggota);
new ConfigDB().aturLebarKolom(JTableAnggota, LebarKolom);
}
} catch (Exception e) {
System.out.print(e.toString());
}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbJKLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJKLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJKLActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
if (
(txtID.getText().isEmpty()) &&(txtNama.getText().isEmpty()) && (txtTempat.getText().isEmpty())
&& (txtTgl.getDate().equals(null)) && (txtAlamat.getText().isEmpty()) && (txtTelp.getText().isEmpty())
&& (cmbJKL.getSelectedItem()==".: Pilih Data :.") && (cmbStatus.getSelectedItem()==".: Pilih Data :.")
) {
JOptionPane.showMessageDialog(null,"Silahkan pilih data sebelum proses hapus ");
JTableAnggota.requestFocus();
} else{
String SQL="DELETE FROM anggota WHERE IDAnggota='"+txtID.getText()+"'";
new ConfigDB().ubahData(SQL);
new ConfigDB().tampilTabel(judulKolom, sqlAnggota, JTableAnggota);
new ConfigDB().aturLebarKolom(JTableAnggota, LebarKolom);
}
} catch (Exception e) {
System.out.print(e.toString());
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        txtID.setText(null);
        txtNama.setText(null);
        txtTempat.setText(null);
        txtTelp.setText(null);
        txtAlamat.setText(null);
        cmbJKL.setSelectedItem(".: Pilih Data :.");
        cmbStatus.setSelectedItem(".: Pilih Data :.");
        txtTgl.setDate(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new ConfigDB().tampilTabel(judulKolom, sqlAnggota, JTableAnggota);
        new ConfigDB().aturLebarKolom(JTableAnggota, LebarKolom);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:
        try {
String SQL="SELECT*FROM anggota WHERE nama like '%"+txtCari.getText()+"%'";
new ConfigDB().cariData(judulKolom, SQL, JTableAnggota);
new ConfigDB().aturLebarKolom(JTableAnggota, LebarKolom);
} catch (Exception e) {
System.out.print(e.toString());
}
    }//GEN-LAST:event_txtCariKeyPressed

    private void JTableAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableAnggotaMouseClicked
        // TODO add your handling code here:
        try {
int baris =JTableAnggota.getSelectedRow();
txtID.setText(String.valueOf(JTableAnggota.getValueAt(baris,0)));
txtNama.setText(String.valueOf(JTableAnggota.getValueAt(baris,1)));
txtTempat.setText(String.valueOf(JTableAnggota.getValueAt(baris,2)));
SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
txtTgl.setDate(dt.parse(String.valueOf(JTableAnggota.getValueAt(baris,3))));
cmbJKL.setSelectedItem(String.valueOf(JTableAnggota.getValueAt(baris, 4)));
cmbStatus.setSelectedItem(String.valueOf(JTableAnggota.getValueAt(baris, 5)));
txtAlamat.setText(String.valueOf(JTableAnggota.getValueAt(baris, 6)));
txtTelp.setText(String.valueOf(JTableAnggota.getValueAt(baris,7)));
} catch (Exception e) {
System.out.print(e.toString());
}
    }//GEN-LAST:event_JTableAnggotaMouseClicked

    private void txtTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formAnggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableAnggota;
    private javax.swing.JComboBox<String> cmbJKL;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtTempat;
    private com.toedter.calendar.JDateChooser txtTgl;
    // End of variables declaration//GEN-END:variables
}
